eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
server.port=8090

# ================== INVENTORY ==================
spring.cloud.gateway.routes[0].id=inventory-service
spring.cloud.gateway.routes[0].uri=lb://inventory-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/inventory/**,/inventory/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/inventory/(?<segment>.*),/${segment}


# ================== ORDER ==================
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://order-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/orders/**,/order/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/order/(?<segment>.*),/${segment}


# ================== PRODUCT ==================
spring.cloud.gateway.routes[2].id=product-service
spring.cloud.gateway.routes[2].uri=lb://product-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/products/**,/product/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/product/(?<segment>.*),/${segment}


# ================== PAYMENT ==================
spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=lb://payment-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/payments/**,/payment/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/payment/(?<segment>.*),/${segment}


# ================== CART ==================
spring.cloud.gateway.routes[4].id=cart-service
spring.cloud.gateway.routes[4].uri=lb://cart-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/carts/**,/cart/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/cart/(?<segment>.*),/${segment}


# ================== USER ==================
spring.cloud.gateway.routes[5].id=user-service
spring.cloud.gateway.routes[5].uri=lb://user-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/users/**,/api/v1/roles/**,/api/v1/addresses/**,/user/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/user/(?<segment>.*),/${segment}


# ================== AUTH ==================
spring.cloud.gateway.routes[6].id=auth-service
spring.cloud.gateway.routes[6].uri=lb://auth-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/auth/**,/auth/**
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/auth/(?<segment>.*),/${segment}


# ================== SWAGGER AGGREGATION ==================
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/user/v3/api-docs

springdoc.swagger-ui.urls[2].name=Product Service
springdoc.swagger-ui.urls[2].url=/product/v3/api-docs

springdoc.swagger-ui.urls[3].name=Order Service
springdoc.swagger-ui.urls[3].url=/order/v3/api-docs

springdoc.swagger-ui.urls[4].name=Inventory Service
springdoc.swagger-ui.urls[4].url=/inventory/v3/api-docs

springdoc.swagger-ui.urls[5].name=Cart Service
springdoc.swagger-ui.urls[5].url=/cart/v3/api-docs

springdoc.swagger-ui.urls[6].name=Payment Service
springdoc.swagger-ui.urls[6].url=/payment/v3/api-docs
