eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
server.port=8090

# Inventory Service
spring.cloud.gateway.routes[0].id=inventory-service
spring.cloud.gateway.routes[0].uri=lb://inventoryService
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/inventorys/**,/inventorys/v3/api-docs
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/inventorys/v3/api-docs,/v3/api-docs

# Order Service
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://orderService
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/orders/**,/order/v3/api-docs
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/order/v3/api-docs,/v3/api-docs

# Product Service
spring.cloud.gateway.routes[2].id=product-service
spring.cloud.gateway.routes[2].uri=lb://productService
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/products/**,/product/v3/api-docs
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/product/v3/api-docs,/v3/api-docs

# Payment Service
spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=lb://paymentService
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/payments/**,/payment/v3/api-docs
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/payment/v3/api-docs,/v3/api-docs

# Cart Service
spring.cloud.gateway.routes[4].id=cart-service
spring.cloud.gateway.routes[4].uri=lb://cartService
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/carts/**,/cart/v3/api-docs
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/cart/v3/api-docs,/v3/api-docs

# User Service
spring.cloud.gateway.routes[5].id=user-service
spring.cloud.gateway.routes[5].uri=lb://userService
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/users/**,/api/v1/roles/**,/api/v1/addresses/**,/user/v3/api-docs
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/user/v3/api-docs,/v3/api-docs

# Auth Service
spring.cloud.gateway.routes[6].id=auth-service
spring.cloud.gateway.routes[6].uri=lb://authService
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/auth/**,/auth/v3/api-docs
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/auth/v3/api-docs,/v3/api-docs

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/user/v3/api-docs

springdoc.swagger-ui.urls[2].name=Product Service
springdoc.swagger-ui.urls[2].url=/product/v3/api-docs

springdoc.swagger-ui.urls[3].name=Order Service
springdoc.swagger-ui.urls[3].url=/order/v3/api-docs

springdoc.swagger-ui.urls[4].name=Inventory Service
springdoc.swagger-ui.urls[4].url=/inventorys/v3/api-docs

springdoc.swagger-ui.urls[5].name=Cart Service
springdoc.swagger-ui.urls[5].url=/cart/v3/api-docs

springdoc.swagger-ui.urls[6].name=Payment Service
springdoc.swagger-ui.urls[6].url=/payment/v3/api-docs
